### ISSUE TITLE
Laravel working on server

### ISSUE THREAD

**Issue by 0reo** [ThrowAwayGames/project-flashbang#1]
make sure laravel is working correctly on prod servers

**Comment by 0reo** [comment]
@andrewellithy, any updates on this?

**Comment by andrewellithy** [comment]
@0reo I just rounded up everything I need and made a script with I will commit in a folder called extrastuff, it will be what installs for http server and one that will install app server. Do we have the domain that will be a VHost? Or do we have a sub domain you would like to use for the time being?

**Comment by 0reo** [comment]
right now we have relhttp.throwawaygames.ca, relapp.throwawaygames.ca, and reldb.throwawaygames.ca.  Can make more as needed, just let me know what you want/need

**Comment by andrewellithy** [comment]
First day was research last night was making script to start and trying to make a model and see how that worked on homestead, made sure my homestead worked, going to have servers ready soon, just need VHOST domain you would like for prod.

**Comment by 0reo** [comment]
location directive was incorrective for /.  changed
try_files $uri $uri/ /index.php$is_args$args =404;
to
try_files $uri $uri/ /index.php?$query_string;
and it's now working
